# fly.toml app configuration file generated for go-example-holy-dust-1768 on 2024-09-10T17:40:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-example-holy-dust-1768'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
